import = [
"/home/ada/.config/alacritty/opacity.toml",
]

[font]
size = 13

[font.bold]
family = "Courier"
style = "Bold"

[font.bold_italic]
family = "Courier"
style = "Bold Italic"

[font.italic]
family = "Courier"
style = "Italic"

[font.normal]
family = "Courier"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
key = "T"
mods = "Control"

[keyboard.bindings.command]
program = "/home/ada/.config/alacritty/themeswitch.sh"

[[keyboard.bindings]]
key = "Up"
mods = "Shift"

[keyboard.bindings.command]
program = "/home/ada/.config/alacritty/opacity.py"
args = ["0.01"]

[[keyboard.bindings]]
key = "Down"
mods = "Shift"

[keyboard.bindings.command]
program = "/home/ada/.config/alacritty/opacity.py"
args = ["-0.01"]

[[keyboard.bindings]]
key = "Right"
mods = "Shift"

[keyboard.bindings.command]
program = "/home/ada/.config/alacritty/opacity.py"
args = ["0.05"]

[[keyboard.bindings]]
key = "Left"
mods = "Shift"

[keyboard.bindings.command]
program = "/home/ada/.config/alacritty/opacity.py"
args = ["-0.05"]

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
